import type { Theme } from '@/types';

export const themes: Theme[] = [
  {
    name: 'termfolio',
    label: 'Termfolio',
    mode: 'dark',
    colors: {
      bg: '#1f2430',
      fg: '#cfd6e4',
      cursor: '#5ccfe6',
      prompt: '#bae67e',
      accent: '#5ccfe6',
      success: '#bae67e',
      error: '#ff6e6e',
      warning: '#ffd580',
      info: '#73d0ff',
      muted: '#8a9199',
      selection: '#34455a',
      border: '#2c3340',
    },
    font: {
      family: '"JetBrains Mono", "Fira Code", "Cascadia Code", monospace',
      size: '14px',
      lineHeight: '1.6',
    },
  },

  {
    name: 'dracula',
    label: 'Dracula',
    mode: 'dark',
    colors: {
      bg: '#282a36',
      fg: '#f8f8f2',
      cursor: '#f8f8f2',
      prompt: '#50fa7b',
      accent: '#bd93f9',
      success: '#50fa7b',
      error: '#ff5555',
      warning: '#f1fa8c',
      info: '#8be9fd',
      muted: '#9099bd',
      selection: '#44475a',
      border: '#44475a',
    },
    font: {
      family: '"JetBrains Mono", "Fira Code", "Cascadia Code", monospace',
      size: '14px',
      lineHeight: '1.6',
    },
  },

  {
    name: 'monokai',
    label: 'Monokai',
    mode: 'dark',
    colors: {
      bg: '#272822',
      fg: '#f8f8f2',
      cursor: '#f8f8f2',
      prompt: '#a6e22e',
      accent: '#ae81ff',
      success: '#a6e22e',
      error: '#f92672',
      warning: '#e6db74',
      info: '#66d9e8',
      muted: '#8f908a',
      selection: '#49483e',
      border: '#75715e',
    },
    font: {
      family: '"JetBrains Mono", "Fira Code", "Cascadia Code", monospace',
      size: '14px',
      lineHeight: '1.6',
    },
  },

  {
    name: 'nord',
    label: 'Nord',
    mode: 'dark',
    colors: {
      bg: '#2e3440',
      fg: '#eceff4',
      cursor: '#eceff4',
      prompt: '#a3be8c',
      accent: '#88c0d0',
      success: '#a3be8c',
      error: '#bf616a',
      warning: '#ebcb8b',
      info: '#88c0d0',
      muted: '#90a0b8',
      selection: '#3b4252',
      border: '#434c5e',
    },
    font: {
      family: '"Fira Code", "JetBrains Mono", "Cascadia Code", monospace',
      size: '14px',
      lineHeight: '1.65',
    },
  },

  {
    name: 'gruvbox-dark',
    label: 'Gruvbox Dark',
    mode: 'dark',
    colors: {
      bg: '#282828',
      fg: '#ebdbb2',
      cursor: '#ebdbb2',
      prompt: '#b8bb26',
      accent: '#d3869b',
      success: '#b8bb26',
      error: '#fb4934',
      warning: '#fabd2f',
      info: '#83a598',
      muted: '#a89984',
      selection: '#3c3836',
      border: '#504945',
    },
    font: {
      family: '"JetBrains Mono", "Fira Code", "Cascadia Code", monospace',
      size: '14px',
      lineHeight: '1.6',
    },
  },

  {
    name: 'tokyo-night',
    label: 'Tokyo Night',
    mode: 'dark',
    colors: {
      bg: '#1a1b26',
      fg: '#c0caf5',
      cursor: '#7dcfff',
      prompt: '#9ece6a',
      accent: '#7aa2f7',
      success: '#9ece6a',
      error: '#f7768e',
      warning: '#ff9e64',
      info: '#7dcfff',
      muted: '#565f89',
      selection: '#2d3f76',
      border: '#29355a',
    },
    font: {
      family: '"JetBrains Mono", "Fira Code", "Cascadia Code", monospace',
      size: '14px',
      lineHeight: '1.65',
    },
  },

  {
    name: 'one-dark',
    label: 'One Dark',
    mode: 'dark',
    colors: {
      bg: '#282c34',
      fg: '#abb2bf',
      cursor: '#528bff',
      prompt: '#98c379',
      accent: '#61afef',
      success: '#98c379',
      error: '#e06c75',
      warning: '#e5c07b',
      info: '#56b6c2',
      muted: '#9098b0',
      selection: '#3e4451',
      border: '#3e4451',
    },
    font: {
      family: '"JetBrains Mono", "Fira Code", "Cascadia Code", monospace',
      size: '14px',
      lineHeight: '1.6',
    },
  },

  {
    name: 'solarized-dark',
    label: 'Solarized Dark',
    mode: 'dark',
    colors: {
      bg: '#002b36',
      fg: '#eee8d5',
      cursor: '#eee8d5',
      prompt: '#859900',
      accent: '#268bd2',
      success: '#859900',
      error: '#dc322f',
      warning: '#b58900',
      info: '#2aa198',
      muted: '#839496',
      selection: '#073642',
      border: '#073642',
    },
    font: {
      family: '"Fira Code", "JetBrains Mono", "Cascadia Code", monospace',
      size: '14px',
      lineHeight: '1.65',
    },
  },

  {
    name: 'hacker',
    label: 'Hacker',
    mode: 'dark',
    colors: {
      bg: '#0d0d0d',
      fg: '#33ff00',
      cursor: '#33ff00',
      prompt: '#33ff00',
      accent: '#00cc44',
      success: '#33ff00',
      error: '#ff3300',
      warning: '#ffcc00',
      info: '#00ccff',
      muted: '#1aaa00',
      selection: '#004400',
      border: '#1a3300',
    },
    font: {
      family: '"Cascadia Code", "JetBrains Mono", "Fira Code", monospace',
      size: '14px',
      lineHeight: '1.6',
    },
  },

  {
    name: 'gruvbox-light',
    label: 'Gruvbox Light',
    mode: 'light',
    colors: {
      bg: '#fbf1c7',
      fg: '#3c3836',
      cursor: '#282828',
      prompt: '#79740e',
      accent: '#8f3f71',
      success: '#79740e',
      error: '#9d0006',
      warning: '#b57614',
      info: '#076678',
      muted: '#665c54',
      selection: '#d5c4a1',
      border: '#bdae93',
    },
    font: {
      family: '"JetBrains Mono", "Fira Code", "Cascadia Code", monospace',
      size: '14px',
      lineHeight: '1.6',
    },
  },

  {
    name: 'solarized-light',
    label: 'Solarized Light',
    mode: 'light',
    colors: {
      bg: '#fdf6e3',
      fg: '#002b36',
      cursor: '#002b36',
      prompt: '#2aa198',
      accent: '#268bd2',
      success: '#2aa198',
      error: '#dc322f',
      warning: '#b58900',
      info: '#268bd2',
      muted: '#546e7a',
      selection: '#eee8d5',
      border: '#ddd6c1',
    },
    font: {
      family: '"Fira Code", "JetBrains Mono", "Cascadia Code", monospace',
      size: '14px',
      lineHeight: '1.65',
    },
  },

  {
    name: 'light',
    label: 'Light',
    mode: 'light',
    colors: {
      bg: '#ffffff',
      fg: '#1a1a1a',
      cursor: '#1a1a1a',
      prompt: '#0a5c36',
      accent: '#1a56db',
      success: '#057a55',
      error: '#c81e1e',
      warning: '#9f580a',
      info: '#1a56db',
      muted: '#6b7280',
      selection: '#dbeafe',
      border: '#e5e7eb',
    },
    font: {
      family: '"JetBrains Mono", "Fira Code", "Cascadia Code", monospace',
      size: '14px',
      lineHeight: '1.6',
    },
  },

  {
    name: 'matrix',
    label: 'Matrix',
    mode: 'dark',
    experimental: true,
    colors: {
      bg: '#000000',
      fg: '#00ff41',
      cursor: '#00ff41',
      prompt: '#00ff41',
      accent: '#00b32c',
      success: '#00ff41',
      error: '#ff0000',
      warning: '#ffff00',
      info: '#00ffff',
      muted: '#008f11',
      selection: '#003b00',
      border: '#003b00',
    },
    font: {
      family: '"Cascadia Code", "JetBrains Mono", "Fira Code", monospace',
      size: '14px',
      lineHeight: '1.6',
    },
  },

  {
    name: 'retro',
    label: 'Retro CRT',
    mode: 'dark',
    experimental: true,
    colors: {
      bg: '#1a0a00',
      fg: '#ff8c00',
      cursor: '#ff8c00',
      prompt: '#ffa500',
      accent: '#ff6600',
      success: '#ffa500',
      error: '#ff2200',
      warning: '#ffcc00',
      info: '#ff9900',
      muted: '#cc7000',
      selection: '#3d1f00',
      border: '#3d1f00',
    },
    font: {
      family: '"Courier New", "Cascadia Code", monospace',
      size: '14px',
      lineHeight: '1.7',
    },
  },
];
